### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length 5; 2 is required

### ISSUE THREAD

**Issue by Lofalt** [CharlesLiu7/Weibo-SuperTopic-Album-Crawler#1]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from weibo.api import WeiboApi
  File "C:\Users\admin\Weibo-SuperTopic-Album-Crawler-master\weibo\api.py", line 33, in <module>
    class WeiboApi(object):
  File "C:\Users\admin\Weibo-SuperTopic-Album-Crawler-master\weibo\api.py", line 39, in WeiboApi
    COOKIES = _load_cookies()
  File "C:\Users\admin\Weibo-SuperTopic-Album-Crawler-master\weibo\api.py", line 30, in _load_cookies
    return dict([l.split('=') for l in settings.COOKIES.split('; ')])
ValueError: dictionary update sequence element #0 has length 5; 2 is required

这是哪里出错了@_@

**Comment by CharlesLiu7** [comment]
你配置文件`settings.py`中`COOKIES`变量有问题

Cookie的字符串形式是以`;`分隔的几个键值对，键值之间用`=`匹配；以下是一个`settings.py`里Cookie配置的例子：

```
COOKIES = 'SCF=AnQRCWnDpobumggGnGJ8qE9OU6oUCyNX0E4PT81OaD_qt9eUYKuBgD39I52hqgDWi3KDG-YAUk5OfA6G2cLt54w.; SSOLoginState=1543621391; SUB=_2A25xBbtfDeRhGeVK7VIT9S7MyDyIHXVSCcUXrDV6PUJbkdBeLUzgkW1NTF6r50ts54N18AX24NZ_eAjSrgwUoyP6; SUHB=0D-10QariE96LZ'
```

上面是原因，下面是具体建议：
不推荐直接复制 浏览器控制台`document.cookie`字符串，建议手动配置以下四个变量`SCF`, `SSOLoginState`, `SUB`, `SUHB`，变量的获取方法如 [图片](https://wx2.sinaimg.cn/mw690/e3aaf28fly1g4op778nbrj21hc0u0qh9.jpg) 所示
